version: 2

updates:
  - package-ecosystem: "docker"
    directory: /
    schedule:
      interval: "weekly"
    # ignore major updates
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
